apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-web-deployment 
  labels: 
    app: nginx-web
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: nginx-web 
  template: 
    metadata: 
      labels: 
        app: nginx-web 
    spec: 
     containers: 
     - name: nginx-web 
       image: nginx:1.14.2 
       ports: 
       - containerPort: 80